version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: QuasarPass123
      ACCEPT_EULA: "Y"
    volumes:
      - ./Quasar.Server.MsSql:/var/opt/mssql/data
    ports:
      - 1433:1433

  quasar.server:
    image: ${DOCKER_REGISTRY-}quasarserver
    build:
      context: .
      dockerfile: Quasar.Server/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - mssql
